apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: us.gcr.io/ticketing-dev-486505/auth
          resources:
            limits:
              cpu: "200m"      # Max 20% of one CPU core
              memory: "256Mi"  # Max 256MB RAM
            requests:
              cpu: "100m"      # Minimum guaranteed CPU
              memory: "128Mi"  # Minimum guaranteed RAM
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000 